spring.application.name=MovieConfigServer

server.port=8888

# Point to your Git repo containing config files
spring.cloud.config.server.git.uri=https://github.com/mass17052005/movie-booking-config
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
