spring.application.name=api-gateway
server.port=8085

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Discovery-based routing
spring.cloud.discovery.enabled=true

# Gateway Routes
spring.cloud.gateway.routes[0].id=movie-service
spring.cloud.gateway.routes[0].uri=lb://movie-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/movies/**

spring.cloud.gateway.routes[1].id=booking-service
spring.cloud.gateway.routes[1].uri=lb://booking-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/bookings/**

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,gateway